# config-server/src/main/resources/application.yml
server:
  port: 8888
spring:
  application.name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/Bootcamp/config     # ruta al repo GIT local
          search-paths: .
          default-label: main                 # si tu rama es main
          clone-on-start: true
management.endpoints.web.exposure.include: health,info

